#!/usr/bin/env python3
"""Gera todas as páginas estáticas do OSWork v2 a partir do conteúdo autoral."""
import sys,json,re,html,os,textwrap
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT))
from conteudo.modulos import MODULES,TRACKS
E=html.escape
SOURCES=[('Modelos e disponibilidade','https://learn.chatgpt.com/docs/models'),('ChatGPT Work','https://learn.chatgpt.com/docs/get-started-with-work'),('Instalação e uso do Codex','https://learn.chatgpt.com/docs/codex/cli'),('Autenticação','https://learn.chatgpt.com/docs/auth'),('Instruções AGENTS.md','https://learn.chatgpt.com/docs/agent-configuration/agents-md'),('Skills locais','https://learn.chatgpt.com/docs/build-skills'),('Git pull','https://git-scm.com/docs/git-pull'),('Telegram Bot API','https://core.telegram.org/bots/api'),('Ubuntu: segurança e firewall','https://documentation.ubuntu.com/server/how-to/security/firewalls/')]
COLORS=['#34d399','#60a5fa','#c084fc','#fbbf24']
SNIPPETS=[('Ficha de comparação','Tarefa: resumir reunião fictícia\nEntrada: pauta com 5 itens\nCritérios: preservar 5 itens; não inventar prazos\nModelo / esforço: anote o que está disponível\nResultado observado: registre os acertos e erros\nEscolha: justifique pelo resultado, não pelo nome'),('Contrato de tarefa','Objetivo: preparar uma pauta revisável\nEntrada: entradas/reuniao.txt\nSaída: saidas/pauta.md\nLimites: não enviar mensagens; não inventar datas\nVerificação: os 5 itens originais continuam presentes\nParada: entregue o arquivo e relate as pendências'),('Bash · Linux ou macOS','mkdir -p ~/projetos/meu-primeiro-projeto\ncd ~/projetos/meu-primeiro-projeto\npwd\ncodex --version\ncodex login\ncodex login status\ncodex'),('Estrutura de trabalho','~/projetos/\n├── config/\n│   ├── memoria.md\n│   ├── falhas.md\n│   ├── dicas.md\n│   └── decisoes.md\n└── meu-primeiro-projeto/\n    ├── AGENTS.md\n    ├── README.md\n    ├── .gitignore\n    ├── entradas/\n    └── saidas/'),('Skill de exemplo','---\nname: relatorio-semanal\ndescription: Gerar rascunho de relatório a partir de CSV fornecido, sem envio externo.\n---\n1. Leia o README e o CSV informado.\n2. Valide cabeçalho, valores e linhas vazias.\n3. Calcule os totais sem inventar dados ausentes.\n4. Gere Markdown com fontes, total e pendências.\n5. Compare o total com a soma das entradas.\n6. Pare antes de enviar ou publicar.'),('Git · somente na pasta de treino','git init -b main\ngit config user.name "Seu Nome"\ngit config user.email "seu-email"\ngit status\ngit add README.md .gitignore\ngit diff --cached\ngit commit -m "Registra estrutura inicial de treino"\ngit log --oneline'),('Bot · dentro de materiais/bot','python3 bot.py --self-test\ncp .env.example .env\nchmod 600 .env\n# Edite .env localmente; nunca compartilhe valores.\npython3 bot.py --identify\n# Preencha ALLOWED_USER_IDS com seu ID e encerre identificação.\npython3 bot.py'),('VPS Ubuntu · adapte caminhos antes','sudo apt update\nsudo apt upgrade\nsudo apt install git python3\n# Adapte a unidade do kit ao usuário e caminho reais.\nsudo systemctl daemon-reload\nsudo systemctl enable --now oswork-bot\nsystemctl status oswork-bot --no-pager\njournalctl -u oswork-bot -n 50 --no-pager')]
for i,m in enumerate(MODULES):
 t=i//2+1;n=i%2+1;m.update(id=f'{t}-{n}',track=t,num=i+1,href=f'curso/trilha{t}/modulo-{t}-{n}.html',time=[30,30,40,35,40,45,50,60][i])
MANIFEST={'course':'oswork-v2','tracks':[{'n':str(t+1),'title':tr[0],'modules':[{'id':m['id'],'title':m['title'],'topics':6,'href':m['href']} for m in MODULES if m['track']==t+1]} for t,tr in enumerate(TRACKS)]}
def url(path,root):return root+path

def diagram(labels,color='#34d399',hero=False):
 rows=[]
 for i,label in enumerate(labels):
  x=20+(i%2)*235;y=25+(i//2)*90
  rows.append(f'<rect x="{x}" y="{y}" width="215" height="65" rx="10" fill="#152234" stroke="{color if i%2==0 else "#38bdf8"}"/><text x="{x+16}" y="{y+25}" fill="#cbd5e1" font-size="10" font-family="monospace">0{i+1} / OSWORK</text><text x="{x+16}" y="{y+47}" fill="#f1f5f9" font-size="14" font-family="sans-serif">{E(label)}</text>')
  if i+2<len(labels):rows.append(f'<path d="M{x+100} {y+65}v25" stroke="{color}" stroke-width="2"/>')
 return f'<svg class="w-full h-auto" viewBox="0 0 490 {50+((len(labels)+1)//2)*90}" role="img" aria-label="{E(" → ".join(labels))}"><defs><filter id="glow"><feGaussianBlur stdDeviation="1"/></filter></defs><path d="M10 10H480V{35+((len(labels)+1)//2)*90}H10Z" fill="none" stroke="#334155" stroke-dasharray="3 7"/>{"".join(rows)}</svg>'

def meter(scope):return f'<div class="meter" data-inema-meter="{scope}" role="progressbar" aria-label="Progresso" aria-valuemin="0" aria-valuemax="100"><span class="inema-meter-pct" data-inema-meter-pct>0%</span><span class="inema-meter-count" data-inema-meter-frac>0 de 0</span></div>'
def page(title,body,dest,track=1):
 root=os.path.relpath(ROOT, (ROOT/dest).parent).replace(os.sep,'/');root='' if root=='.' else root+'/'
 nav=''.join(f'<a href="{root}curso/trilha{i+1}/index.html" '+('aria-current="page"' if track==i+1 else '')+f'>T{i+1}<span class="long"> · {E(t[0])}</span></a>' for i,t in enumerate(TRACKS))
 manifest=json.loads(json.dumps(MANIFEST))
 for tr in manifest['tracks']:
  for m in tr['modules']:m['href']=root+m['href']
 anti="""(function(){try{var p=JSON.parse(localStorage.getItem('inema.prefs')||'{}'),d=document.documentElement;d.classList.toggle('dark',p.theme?p.theme!=='claro':true);if(p.theme)d.dataset.theme=p.theme;if(p.fontScale)d.style.setProperty('--fs-root',p.fontScale+'%');if(p.font)d.dataset.font=p.font;if(p.accent)d.dataset.accent=p.accent;if(p.lineWidth)d.style.setProperty('--measure',p.lineWidth+'ch');if(p.leading)d.style.setProperty('--lh-body',p.leading);}catch(e){document.documentElement.classList.add('dark')}})();"""
 appearance=''.join(f'<button type="button" data-inema-set-theme="{value}">{label}</button>' for value,label in [('inema-dark','Escuro'),('claro','Claro'),('sepia','Sépia'),('foco','Foco'),('contraste','Alto contraste')])
 out=f'''<!doctype html><html lang="pt-BR" class="dark"><head><meta charset="utf-8"><script>{anti}</script>
<meta name="viewport" content="width=device-width,initial-scale=1"><meta name="inema-course" content="oswork-v2"><meta property="og:image" content="https://inematds.github.io/oswork/capa/capa.png"><meta property="og:title" content="OSWork — IA como sistema de trabalho"><meta name="description" content="OSWork: IA como sistema de trabalho. Oito módulos práticos, do chat à operação supervisionada."><title>{E(title)} | OSWork</title>
<script type="application/json" data-inema-manifest>{json.dumps(manifest,ensure_ascii=False)}</script>
<link rel="icon" href="{root}assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="{root}assets/site.css"><link rel="stylesheet" href="{root}assets/learn.css">
<style>:root{{--track:{COLORS[track-1]}}}html:not(.dark){{--track:{['#047857','#1d4ed8','#7e22ce','#92400e'][track-1]}}}</style></head><body>
<a class="skip" href="#conteudo">Pular para conteúdo</a>
<nav class="topnav" aria-label="Navegação principal"><div class="wrap"><div class="nav-main"><a class="brand" href="{root}index.html">OSWork<span aria-hidden="true">_</span></a><span aria-hidden="true">/</span><a class="text-sky-400" href="https://inema.club">INEMA.CLUB</a><span class="spacer"></span><button data-inema-journey-open>Minha jornada</button><button data-inema-appearance-toggle="#aparencia" aria-expanded="false">Aa · Aparência</button><button onclick="toggleTheme()" aria-label="Alternar tema claro e escuro">◐ Tema</button></div><div class="nav-tracks">{nav}<a href="{root}materiais/index.html">Materiais</a></div>
<div id="aparencia" class="appearance" data-inema-appearance hidden><div class="row">{appearance}</div><div class="row"><span>Tamanho</span><button data-inema-set-fontscale="100">100%</button><button data-inema-set-fontscale="112">112%</button><button data-inema-set-fontscale="125">125%</button><button data-inema-set-font="inter">Sem serifa</button><button data-inema-set-font="leitura">Serifa</button><button data-inema-set-linewidth="60">Coluna estreita</button><button data-inema-set-linewidth="75">Coluna ampla</button><button data-inema-set-leading="1.7">Entrelinha confortável</button></div></div></div></nav>
<main id="conteudo" class="wrap">{body}</main><footer><div class="wrap">OSWork · IA como sistema de trabalho · INEMA.CLUB · Edição v2 · v1.0.0<br>Conteúdo revisado em 20/09/2026. Progresso e notas ficam neste navegador; exporte na sua jornada. Em file://, o compartilhamento entre páginas depende do navegador. Use HTTP local para continuidade garantida.<br><a href="{root}FONTES.md">Fontes e revisão técnica</a> · <a href="https://inematds.github.io/oswork-v5/">Conhecer a edição v5</a></div></footer>
<dialog id="module-dialog" aria-labelledby="modal-title"><div class="actions"><strong id="modal-title">Módulo completo</strong><button onclick="document.getElementById('module-dialog').close()">Fechar módulo</button></div><iframe title="Conteúdo completo do módulo"></iframe></dialog>
<script src="{root}assets/learn.js"></script><script src="{root}assets/site.js"></script></body></html>'''
 # Quebras em elementos tornam o HTML inspecionável, sem conteúdo em runtime.
 out=re.sub(r'>(?=<(?:/?(?:html|head|body|nav|div|section|article|h[1-6]|p|span|button|a|ul|li|ol|main|footer|header|table|tr|td|th|thead|tbody|figure|figcaption|details|summary|label|input|script|link|meta|aside|pre|dialog|iframe)\b))','>\n',out)
 out=re.sub(r'(<p[^>]*>)([^<]+)(</p>)',lambda m:m[1]+'\n'+textwrap.fill(m[2],100)+'\n'+m[3],out)
 p=ROOT/dest;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(out)

def sourcebox(indices):return '<div class="sources"><h3>Consulte a fonte</h3><p>Ferramentas verificadas em 20/09/2026; nomes de telas e disponibilidade podem mudar.</p><ul>'+''.join(f'<li><a href="{SOURCES[i][1]}" target="_blank" rel="noopener">{SOURCES[i][0]}</a></li>' for i in indices)+'</ul></div>'
def trackcard(i):
 tr=TRACKS[i];return f'<a class="card" href="curso/trilha{i+1}/index.html"><div class="overline"><span>TRILHA 0{i+1}</span><span>2 MÓDULOS · 12 TÓPICOS</span></div><h2>{E(tr[0])}</h2><p>{E(tr[2])}</p><span class="accent">Explorar trilha →</span></a>'
hero=f'''<header class="hero"><div><p class="kicker">INEMA · FORMAÇÃO PRÁTICA / V2</p><h1>Sua IA precisa de um <span class="accent">sistema.</span></h1><p>Do chat ao seu ambiente de agentes. Organize arquivos, ensine procedimentos e construa rotinas que você consegue verificar.</p><div class="actions"><a class="button primary" href="{MODULES[0]['href']}">Começar pelo primeiro módulo →</a><button data-os-resume>Continuar de onde parei</button></div>{meter('curso')}<p class="help-note">Sem pré-requisito de programação. Laboratórios técnicos explicados passo a passo.</p></div><figure class="hero-panel">{diagram(['MODELO','INTERFACE','ARQUIVOS','INSTRUÇÕES','FERRAMENTAS','MEMÓRIA','AUTOMAÇÕES','REVISÃO'])}<figcaption class="help-note">O resultado depende das conexões entre as peças, não só do modelo.</figcaption></figure></header>'''
body=hero+'<div class="stats"><div><strong>4</strong><span>trilhas de aprendizagem</span></div><div><strong>8</strong><span>módulos completos</span></div><div><strong>48</strong><span>tópicos para estudar</span></div><div><strong>5h30</strong><span>com práticas · estimativa</span></div></div><section class="band"><p class="kicker">SEU PERCURSO</p><h2>Uma bancada de trabalho, peça por peça.</h2><div class="grid">'+''.join(trackcard(i) for i in range(4))+'</div></section><section class="band grid"><div><p class="kicker">O QUE VOCÊ CONSTRÓI</p><h2>Um projeto que continua depois da conversa.</h2><p>Você termina com uma estrutura de pastas, instruções próprias, uma Skill, histórico Git e um bot de consulta restrito. A última trilha ensina a planejar e operar esse serviço numa VPS.</p><p>O bot de laboratório usa regras e dados fictícios. A extensão com IA é apresentada separadamente, com critérios de integração.</p></div><div class="card"><h3>Estude do seu jeito</h3><p>Marque tópicos lidos, registre dúvidas e selecione trechos para anotar. Ajuste tema e tamanho da leitura em Aa. Exporte seu progresso em Minha jornada.</p><a class="button" href="materiais/index.html">Abrir kit de trabalho →</a><p class="help-note">Você pode ler tudo sem conta. Instalações, Telegram e VPS são práticas feitas no seu próprio ambiente.</p></div></section>'
page('IA como sistema de trabalho',body,'index.html')
for t,tr in enumerate(TRACKS,1):
 mods=[m for m in MODULES if m['track']==t]
 body=f'<header class="hero"><div><p class="kicker">TRILHA 0{t} / OSWORK</p><h1>{tr[0]}</h1><p>{tr[2]}</p>{meter("trilha:"+str(t))}</div><figure class="hero-panel">{diagram([x["title"].split(":")[0][:26] for x in mods]+["PRATICAR","CONFERIR"],COLORS[t-1])}<figcaption class="help-note">Leia, aplique numa tarefa pequena e confira o resultado antes de avançar.</figcaption></figure></header><div class="stats"><div><strong>2</strong><span>módulos</span></div><div><strong>12</strong><span>tópicos</span></div><div><strong>{sum(m["time"] for m in mods)} min</strong><span>com prática</span></div><div><strong>Guiado</strong><span>passo a passo</span></div></div><h2>Mapa da trilha</h2><div class="grid">'
 for m in mods:body+=f'<a class="card" href="#modulo-{m["id"]}"><div class="overline"><span>{m["id"].replace("-",".")}</span><span>~{m["time"]} min</span></div><h3>🧭 {m["title"]}</h3><p>{m["goal"]}</p></a>'
 body+='</div><section class="band"><h2 class="text-2xl font-bold">Conteúdo detalhado</h2>'
 for m in mods:
  body+=f'<article class="module-card" id="modulo-{m["id"]}" data-inema-module="{m["id"]}" data-inema-track="{t}"><p class="kicker">MÓDULO {m["id"].replace("-",".")}</p><h2 class="text-2xl font-bold">{m["title"]}</h2><p>{m["goal"]}</p>{meter("modulo:"+m["id"])}'
  for j,tp in enumerate(m['topics'],1):
   pid=f'p-{m["id"]}-{j}';body+=f'<div class="topic-item"><button onclick="toggleTopic(this)" aria-expanded="false" aria-controls="{pid}"><span class="number">{j}</span><span>{tp["title"]}</span></button><div class="topic-explanation" id="{pid}"><h4>O que é</h4><p>{E(tp["what"])}</p><h4>Por que aprender</h4><p>{E(tp["why"])}</p><h4>Conceitos-chave</h4><p>{E(tp["keys"])}</p></div></div>'
  file=Path(m['href']).name
  body+=f'<div class="actions"><a class="button primary" href="{file}">Ver completo →</a><button data-modal-src="{file}">Ver em modal</button></div></article>'
 body+='</section>';page(tr[0],body,f'curso/trilha{t}/index.html',t)
for i,m in enumerate(MODULES):
 t=m['track'];mid=m['id'];topics=m['topics']
 body=f'<div class="breadcrumbs"><a href="../../index.html">Início</a> / <a href="index.html">{TRACKS[t-1][0]}</a> / Módulo {mid.replace("-",".")}</div><article id="modulo-{mid}" data-inema-module="{mid}" data-inema-track="{t}"><header class="hero"><div><p class="kicker">MÓDULO {mid.replace("-",".")} / {m["num"]} DE 8</p><h1>{E(m["title"])}</h1><p>{E(m["goal"])}</p>{meter("modulo:"+mid)}</div><figure class="hero-panel">{diagram([tp["title"][:27] for tp in topics],COLORS[t-1])}<figcaption class="help-note">As seis peças deste módulo. Ao final, você produz uma evidência de aprendizagem.</figcaption></figure></header><div class="stats"><div><strong>6</strong><span>tópicos</span></div><div><strong>~{m["time"]} min</strong><span>leitura e prática</span></div><div><strong>1</strong><span>entrega verificável</span></div><div><strong>Guiado</strong><span>laboratório de treino</span></div></div><div class="reading-layout"><div>'
 for j,tp in enumerate(topics,1):
  body+=f'<section class="topic inema-prose" id="topico-{j}" data-inema-topic="modulo-{mid}#topico-{j}"><h2><span class="number">{j}</span>{E(tp["title"])}</h2><h3>O que é</h3><p data-inema-block="m{mid}-t{j}-p1">{E(tp["what"])}</p><h3>Por que aprender</h3><p data-inema-block="m{mid}-t{j}-p2">{E(tp["why"])}</p><h3>Conceitos-chave</h3><p data-inema-block="m{mid}-t{j}-p3">{E(tp["keys"])}</p><div class="example"><h4>Na prática</h4><p data-inema-block="m{mid}-t{j}-ex">{E(tp["example"])}</p></div>'
  if j in [1,4]:body+=f'<div class="compare"><div><h4>✓ Faça</h4><p>{E(tp["action"])}</p></div><div><h4>✗ Evite</h4><p>{E(["Aceitar uma conclusão sem conferir a entrada que a sustenta.","Misturar a cópia de treino com arquivos privados ou trabalho em produção."][j==4])}</p></div></div>'
  elif j==3:body+=f'<h4>Sequência para experimentar</h4><ol class="timeline"><li>Prepare uma cópia de treino.</li><li>{E(tp["action"])}</li><li>Registre o resultado observado e a próxima correção.</li></ol>'
  else:body+=f'<aside class="tip"><h4>Experimente agora</h4><p>{E(tp["action"])}</p></aside>'
  body+=f'<div class="actions"><button type="button" data-inema-read-toggle aria-pressed="false"><span class="inema-read-icon" aria-hidden="true">○</span><span class="inema-read-label" data-inema-read-label>Marcar como lido</span></button><button type="button" data-inema-doubt-toggle aria-pressed="false">? Tenho dúvida</button></div></section>'
 body+='</div><nav class="toc" data-inema-toc aria-label="Tópicos deste módulo"><p class="kicker">NESTA AULA</p><ul>'+''.join(f'<li><a class="inema-toc-link" href="#topico-{j}">{j}. {E(tp["title"])}</a></li>' for j,tp in enumerate(topics,1))+'</ul><a href="#laboratorio">Laboratório final ↓</a></nav></div>'
 body+='<section class="band"><h2>Critérios para revisar sua entrega</h2><p>Use esta rubrica depois do laboratório. Cada linha pede uma evidência; marcar leitura não significa que a prática foi executada.</p><div class="table-scroll"><table><thead><tr><th>Critério</th><th>Evidência esperada</th><th>Se não passou</th></tr></thead><tbody>'
 for row in [('Escopo','A entrega corresponde ao objetivo desta aula.','Reduza a tarefa e nomeie um único resultado.'),('Entradas','Você sabe quais arquivos ou dados foram usados.','Liste as fontes e remova material sem relação.'),('Execução','O procedimento foi realizado no ambiente de treino.','Diferencie o que foi planejado do que foi feito.'),('Conferência','Um resultado foi comparado com uma referência.','Abra o arquivo ou repita a consulta verificável.'),('Segredos','Nenhum token, senha ou dado privado foi compartilhado.','Revise a cópia de trabalho antes de qualquer envio.'),('Continuidade','Outra pessoa consegue encontrar o próximo passo.','Atualize README e registre uma pendência concreta.')]:
  body+='<tr>'+''.join('<td>'+E(cell)+'</td>' for cell in row)+'</tr>'
 body+='</tbody></table></div></section>'
 body+=f'<section class="lab" id="laboratorio"><p class="kicker">MÃO NA MASSA / ~15 MIN OU EM ETAPAS</p><h2>{E(m["lab"])}</h2><p>Use arquivos fictícios e uma pasta de treino. As práticas com instalação, Telegram ou VPS podem exigir tempo adicional para cadastro e configuração.</p><ol class="checklist">'
 for j,step in enumerate(m['steps'],1):body+=f'<li><label><input type="checkbox" data-task="{mid}-{j}"><span>{E(step)}</span></label></li>'
 body+=f'</ol><h3>{SNIPPETS[i][0]}</h3><p>Leia o bloco antes de usar. Campos como Seu Nome e usuario@ip-da-vps são exemplos para adaptar; comandos administrativos pertencem somente ao seu ambiente de treino.</p><pre><code>{E(SNIPPETS[i][1])}</code></pre><button data-copy-prev>Copiar bloco</button><h3>Critério de pronto</h3><p>{E(m["goal"])} Registre o arquivo produzido, o teste executado e o resultado observado.</p><a class="button" href="../../materiais/index.html">Abrir arquivos e modelos do laboratório</a></section><section class="band"><h2>Confira o que ficou</h2><p>{E(m["check"])}</p><details><summary>Ver resposta comentada</summary><p>{E(m["answer"])}</p><p>Se sua resposta foi diferente, volte ao tópico correspondente e escreva a diferença em uma frase. A checagem não bloqueia seu estudo.</p></details><h3>Resumo do módulo</h3><ul>'+''.join(f'<li>{E(tp["keys"])}</li>' for tp in topics)+'</ul></section>'+sourcebox([[0,3],[1],[2,3],[4],[4,5],[6],[7],[8]][i])
 prev='../../'+MODULES[i-1]['href'] if i else '../../index.html';nxt='../../'+MODULES[i+1]['href'] if i<7 else '../../materiais/index.html'
 body+=f'<div class="actions"><a class="button" href="{prev}">← Anterior</a><a class="button" href="index.html">Voltar à trilha</a><a class="button primary" href="{nxt}">{"Próximo módulo →" if i<7 else "Concluir com o kit →"}</a></div></article>'
 page(m['title'],body,m['href'],t)
materials=[('contrato-de-tarefa.md','Contrato de tarefa'),('README-projeto.md','README do projeto'),('AGENTS-projeto.md','Instruções por projeto'),('AGENTS-global.md','Instruções globais'),('memoria.md','Memória operacional'),('decisoes.md','Registro de decisões'),('falhas.md','Registro de falhas'),('dicas.md','Dicas verificadas'),('SKILL-relatorio.md','Skill de relatório'),('gitignore.txt','Modelo de .gitignore'),('plano-vps.md','Plano de VPS'),('bot/README.md','Manual do bot'),('bot/bot.py','Código do bot'),('bot/.env.example','Variáveis sem segredos'),('bot/oswork-bot.service','Unidade systemd'),('bot/vendas.csv','Dados fictícios')]
body='<header class="hero"><div><p class="kicker">ARQUIVOS DE APOIO</p><h1>Sua bancada começa aqui.</h1><p>Modelos editáveis e exemplos fictícios. Leia cada arquivo antes de adaptar. O bot base funciona sem modelo de IA e tem um teste offline.</p><a class="button primary" href="oswork-kit.zip" download>Baixar kit completo (.zip)</a></div><div class="card"><h2>Três entregas finais</h2><ol><li>Uma pasta organizada com instruções verificáveis.</li><li>Uma alteração registrada e recuperada no Git.</li><li>Um bot restrito e um plano de operação supervisionada.</li></ol></div></header><div class="grid">'+''.join(f'<a class="card" href="{p}" download><h3>{label}</h3><p>{p}</p><span>Baixar arquivo ↓</span></a>' for p,label in materials)+'</div><section class="band"><h2>Como conferir seu aprendizado</h2><p>Entregue README, AGENTS, uma Skill e um registro de verificação sem segredos. Para a etapa de VPS, diferencie o planejamento dos testes realmente executados. Não marque uma implantação como concluída se ela só foi simulada.</p><a href="../index.html">Voltar ao curso</a></section>'
page('Kit de trabalho',body,'materiais/index.html')
(ROOT/'FONTES.md').write_text('# Fontes e revisão técnica\n\nConsulta em 20/09/2026. Conceitos e exemplos autorais; recursos de produto dependem da conta e podem mudar.\n\n'+'\n'.join(f'- [{a}]({b})' for a,b in SOURCES)+'\n\nA VPS não garante disponibilidade sozinha. O bot incluído é determinístico; não promete um agente de IA já integrado. Login ChatGPT e API são modalidades distintas. “Sistema operacional” é metáfora de organização do trabalho.\n')
print('Geradas 14 páginas: início, 4 trilhas, 8 módulos e materiais.')
